# Generated by Django 3.1.1 on 2020-09-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(verbose_name='Quantidade de pontos')),
                ('min_season', models.PositiveIntegerField(verbose_name='Menor quantidade de pontos')),
                ('max_season', models.PositiveIntegerField(verbose_name='Maior quantidade de pontos')),
                ('break_min_record_amount', models.PositiveIntegerField(verbose_name='Quantidade de vezes que o recorde minimo foi quebrado')),
                ('break_max_record_amount', models.PositiveIntegerField(verbose_name='Quantidade de vezes que o recorde máximo foi quebrado')),
                ('is_min_break_record', models.BooleanField(null=True, verbose_name='Houve querba de recorde mínimo?')),
                ('is_max_break_record', models.BooleanField(null=True, verbose_name='Houve quebra de recorde máximo?')),
            ],
        ),
    ]
