# Generated by Django 3.0.8 on 2020-09-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='break_max_record_amount',
            field=models.PositiveIntegerField(blank=True, verbose_name='Quantidade de vezes que o recorde máximo foi quebrado'),
        ),
        migrations.AlterField(
            model_name='games',
            name='break_min_record_amount',
            field=models.PositiveIntegerField(blank=True, verbose_name='Quantidade de vezes que o recorde minimo foi quebrado'),
        ),
        migrations.AlterField(
            model_name='games',
            name='is_max_break_record',
            field=models.BooleanField(blank=True, null=True, verbose_name='Houve quebra de recorde máximo?'),
        ),
        migrations.AlterField(
            model_name='games',
            name='is_min_break_record',
            field=models.BooleanField(blank=True, null=True, verbose_name='Houve querba de recorde mínimo?'),
        ),
        migrations.AlterField(
            model_name='games',
            name='max_season',
            field=models.PositiveIntegerField(blank=True, verbose_name='Maior quantidade de pontos'),
        ),
        migrations.AlterField(
            model_name='games',
            name='min_season',
            field=models.PositiveIntegerField(blank=True, verbose_name='Menor quantidade de pontos'),
        ),
    ]
