# Generated by Django 3.1.1 on 2020-09-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200929_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do jogo'),
        ),
    ]
